define(['js/ParthenonApp', 'js/filter/RangeFilter', 'js/service/PlayerService'], function(app) {
    "use strict";
    app.controller('PlayerController',
            ['$scope', '$timeout', 'PlayerService', function($scope, $timeout, PlayerService) {

        /** Fetch updated list of players from server every few seconds. */
        $scope.players = [];
        (function getPlayers() {
            PlayerService.getPlayers().$promise.then(function(result) {
                $scope.players = result;
                $timeout(getPlayers, 2500);
            });
        })();

        /** Keep track of players that are considered "selected". */
        $scope.selectedPlayers = [];
        $scope.toggleSelectedPlayer = function(name) {
            if ($scope.isSelectedPlayer(name)) {
                $scope.selectedPlayers.splice($scope.selectedPlayers.indexOf(name), 1);
            } else {
                $scope.selectedPlayers.push(name);
            }
        };
        $scope.isSelectedPlayer = function(name) {
            return $scope.selectedPlayers.indexOf(name) !== -1;
        };

        /** Return true if the player is considered dead */
        $scope.isDead = function(player) {
            return player.online && Math.floor(player.health) === 0;
        };

        /** Returns the number of full heart icons used to represent the player's health. */
        $scope.numFullHeartIcons = function(health) {
            return Math.floor(Math.round(health)/2);
        };
        /** Returns the number of half heart icons used to represent the player's health. */
        $scope.numHalfHeartIcons = function(health) {
            return parseInt(Math.round(health)) % 2;
        };
        /** Returns the number of empty heart icons used to represent the player's health. */
        $scope.numEmptyHeartIcons = function(health) {
            return 10 - $scope.numFullHeartIcons(Math.round(health)) - $scope.numHalfHeartIcons(Math.round(health));
        };

        /** Returns the number of full hunger icons used to represent the player's health. */
        $scope.numFullHungerIcons = function(foodLevel) {
            return Math.floor(foodLevel/2);
        };
        /** Returns the number of half hunger icons used to represent the player's health. */
        $scope.numHalfHungerIcons = function(foodLevel) {
            return foodLevel % 2;
        };
        /** Returns the number of empty hunger icons used to represent the player's health. */
        $scope.numEmptyHungerIcons = function(foodLevel) {
            return 10 - $scope.numFullHungerIcons(foodLevel) - $scope.numHalfHungerIcons(foodLevel);
        };

        /** Returns the individual digits of the player's experience level. */
        $scope.expLevelDigits = function(expLevel) {
            return expLevel <= 0 ? [] : expLevel.toString().split('');
        };

        $scope.isHeldInMainHand = function(item) {
            return item.type === "HELD_IN_MAIN_HAND";
        };
        $scope.isHeldInOffHand = function(item) {
            return item.type === "HELD_IN_OFF_HAND";
        };
        $scope.isEquippedBoots = function(item) {
            return item.type === "EQUIPPED_BOOTS";
        };
        $scope.isEquippedChestplate = function(item) {
            return item.type === "EQUIPPED_CHESTPLATE";
        };
        $scope.isEquippedHelmet = function(item) {
            return item.type === "EQUIPPED_HELMET";
        };
        $scope.isEquippedLeggings = function(item) {
            return item.type === "EQUIPPED_LEGGINGS";
        };
        $scope.isGeneral = function(item) {
            return item.type === "GENERAL";
        };

        /** Converts the given item name into a CSS-friendly name. The conversion is similar
         *  to the one done in the inventory icon Lua script. */
        $scope.toCssItemName = function(itemName) {
            return itemName.replace(/ANVIL\([0-9]+\)/, "ANVIL")
                           .replace(/SWORD\([0-9]+\)/, "SWORD")
                           .replace(/BOW\([0-9]+\)/, "BOW")
                           .replace(/PICKAXE\([0-9]+\)/, "PICKAXE")
                           .replace(/SPADE\([0-9]+\)/, "SPADE")
                           .replace(/AXE\([0-9]+\)/, "AXE")
                           .replace(/HOE\([0-9]+\)/, "HOE")
                           .replace(/HELMET\([0-9]+\)/, "HELMET")
                           .replace(/CHESTPLATE\([0-9]+\)/, "CHESTPLATE")
                           .replace(/LEGGINGS\([0-9]+\)/, "LEGGINGS")
                           .replace(/BOOTS\([0-9]+\)/, "BOOTS")
                           .replace(/SHEARS\([0-9]+\)/, "SHEARS")
                           .replace(/SADDLE\([0-9]+\)/, "SADDLE")
                           .replace(/SHIELD\([0-9]+\)/, "SHIELD")
                           .replace(/FISHING_ROD\([0-9]+\)/, "FISHING_ROD")
                           .replace(/FLINT_AND_STEEL\([0-9]+\)/, "FLINT_AND_STEEL")
                           .replace(/long_/, "")
                           .replace(/strong_/, "")
                           .replace(/ facing[a-zA-Z0-9 ]*/, "")
                           .replace(/[ \(\)=\/]/g, "_")
                           .replace(/_/g, "");
        };

        $scope.toFriendlyItemName = function(cssItemName) {
            return spigotNameToFriendlyName[cssItemName].replace(/ /g,  "_");
        };

        /* Generated by ../WEB-INF/scrips/inventory_icon.lua */
        var spigotNameToFriendlyName = {
            "RECORD110": "11 Disc",
            "GOLDRECORD0": "13 Disc",
            "BOATACACIA0": "Acacia Boat",
            "ACACIADOORITEM0": "Acacia Door",
            "ACACIAFENCE0": "Acacia Fence",
            "ACACIAFENCEGATECLOSED": "Acacia Fence Gate",
            "ACACIADECAYABLEACACIALEAVES20": "Acacia Leaves",
            "ACACIAACACIASAPLING4": "Acacia Sapling",
            "ACACIAUPACACIALOG20": "Acacia Wood",
            "ACACIAWOOD4": "Acacia Wood Planks",
            "ACACIAWOODSTEP4ACACIA": "Acacia Wood Slab",
            "ACACIASTAIRS0": "Acacia Wood Stairs",
            "ACTIVATORRAIL0": "Activator Rail",
            "REDROSE2": "Allium",
            "STONE5": "Andesite",
            "ANVIL": "Anvil",
            "APPLE0": "Apple",
            "ARMORSTAND0": "Armor Stand",
            "ARROW0": "Arrow",
            "TIPPEDARROWfireresistance": "Arrow of Fire Resistance",
            "TIPPEDARROWharming": "Arrow of Harming",
            "TIPPEDARROWhealing": "Arrow of Healing",
            "TIPPEDARROWinvisibility": "Arrow of Invisibility",
            "TIPPEDARROWleaping": "Arrow of Leaping",
            "TIPPEDARROWluck": "Arrow of Luck",
            "TIPPEDARROWnightvision": "Arrow of Night Vision",
            "TIPPEDARROWpoison": "Arrow of Poison",
            "TIPPEDARROWregeneration": "Arrow of Regeneration",
            "TIPPEDARROWslowness": "Arrow of Slowness",
            "TIPPEDARROWwater": "Arrow of Splashing",
            "TIPPEDARROWstrength": "Arrow of Strength",
            "TIPPEDARROWswiftness": "Arrow of Swiftness",
            "TIPPEDARROWwaterbreathing": "Arrow of Water Breathing",
            "TIPPEDARROWweakness": "Arrow of Weakness",
            "LINGERINGPOTIONawkward": "Awkward Lingering Potion",
            "POTIONawkward": "Awkward Potion",
            "SPLASHPOTIONawkward": "Awkward Splash Potion",
            "REDROSE3": "Azure Bluet",
            "BAKEDPOTATO0": "Baked Potato",
            "BEACON0": "Beacon",
            "BED0": "Bed",
            "BEDROCK0": "Bedrock",
            "BEETROOT0": "Beetroot",
            "BEETROOTSEEDS0": "Beetroot Seeds",
            "BEETROOTSOUP0": "Beetroot Soup",
            "BOATBIRCH0": "Birch Boat",
            "BIRCHDOORITEM0": "Birch Door",
            "BIRCHFENCE0": "Birch Fence",
            "BIRCHFENCEGATECLOSED": "Birch Fence Gate",
            "BIRCHDECAYABLEBIRCHLEAVES2": "Birch Leaves",
            "BIRCHBIRCHSAPLING2": "Birch Sapling",
            "BIRCHUPBIRCHLOG2": "Birch Wood",
            "BIRCHWOOD2": "Birch Wood Planks",
            "BIRCHWOODSTEP2BIRCH": "Birch Wood Slab",
            "BIRCHWOODSTAIRS0": "Birch Wood Stairs",
            "BANNER0": "Black Banner",
            "CARPET15": "Black Carpet",
            "STAINEDCLAY15": "Black Hardened Clay",
            "STAINEDGLASS15": "Black Stained Glass",
            "STAINEDGLASSPANE15": "Black Stained Glass Pane",
            "BLACKWOOL15": "Black Wool",
            "BLAZEPOWDER0": "Blaze Powder",
            "BLAZEROD0": "Blaze Rod",
            "COALBLOCK0": "Block of Coal",
            "DIAMONDBLOCK0": "Block of Diamond",
            "EMERALDBLOCK0": "Block of Emerald",
            "GOLDBLOCK0": "Block of Gold",
            "IRONBLOCK0": "Block of Iron",
            "QUARTZBLOCK0": "Block of Quartz",
            "REDSTONEBLOCK0": "Block of Redstone",
            "BANNER4": "Blue Banner",
            "CARPET11": "Blue Carpet",
            "STAINEDCLAY11": "Blue Hardened Clay",
            "REDROSE1": "Blue Orchid",
            "STAINEDGLASS11": "Blue Stained Glass",
            "STAINEDGLASSPANE11": "Blue Stained Glass Pane",
            "BLUEWOOL11": "Blue Wool",
            "BONE0": "Bone",
            "BONEBLOCK0": "Bone Block",
            "WHITEDYE15": "Bone Meal",
            "BOOK0": "Book",
            "BOOKANDQUILL0": "Book and Quill",
            "BOOKSHELF0": "Bookshelf",
            "EXPBOTTLE0": "Bottle o' Enchanting",
            "BOW": "Bow",
            "BOWL0": "Bowl",
            "BREAD0": "Bread",
            "BREWINGSTANDITEM0": "Brewing Stand",
            "CLAYBRICK0": "Brick",
            "BRICKSTAIRS0": "Brick Stairs",
            "BRICK0": "Bricks",
            "BRICKSTEP4": "Bricks Slab",
            "BANNER3": "Brown Banner",
            "CARPET12": "Brown Carpet",
            "STAINEDCLAY12": "Brown Hardened Clay",
            "BROWNMUSHROOM0": "Brown Mushroom",
            "STAINEDGLASS12": "Brown Stained Glass",
            "STAINEDGLASSPANE12": "Brown Stained Glass Pane",
            "BROWNWOOL12": "Brown Wool",
            "BUCKET0": "Bucket",
            "CACTUS0": "Cactus",
            "GREENDYE2": "Cactus Green",
            "CAKE0": "Cake",
            "CARROTITEM0": "Carrot",
            "CARROTSTICK0": "Carrot on a Stick",
            "CAULDRONITEM0": "Cauldron",
            "CHAINMAILBOOTS": "Chain Boots",
            "CHAINMAILCHESTPLATE": "Chain Chestplate",
            "CHAINMAILHELMET": "Chain Helmet",
            "CHAINMAILLEGGINGS": "Chain Leggings",
            "CHEST0": "Chest",
            "QUARTZBLOCK1": "Chiseled Quartz Block",
            "REDSANDSTONE1": "Chiseled Red Sandstone",
            "GLYPHEDSANDSTONE1": "Chiseled Sandstone",
            "SMOOTHBRICKSMOOTHBRICK3": "Chiseled Stone Bricks",
            "STONEMONSTEREGGS5": "Chiseled Stone Bricks Monster Egg",
            "CHORUSFLOWER0": "Chorus Flower",
            "CHORUSFRUIT0": "Chorus Fruit",
            "CHORUSPLANT0": "Chorus Plant",
            "CLAYBALL0": "Clay",
            "CLAY0": "Clay (block)",
            "WATCH0": "Clock",
            "RAWFISH2": "Clownfish",
            "COALORE0": "Coal Ore",
            "DIRT1": "Coarse Dirt",
            "COBBLESTONE0": "Cobblestone",
            "COBBLESTONEMONSTEREGGS1": "Cobblestone Monster Egg",
            "COBBLESTONESTEP3": "Cobblestone Slab",
            "COBBLESTONESTAIRS0": "Cobblestone Stairs",
            "COBBLEWALL0": "Cobblestone Wall",
            "WEB0": "Cobweb",
            "BROWNDYE3": "Cocoa Beans",
            "COMPASS0": "Compass",
            "COOKEDCHICKEN0": "Cooked Chicken",
            "COOKEDFISH0": "Cooked Fish",
            "COOKEDMUTTON0": "Cooked Mutton",
            "GRILLEDPORK0": "Cooked Porkchop",
            "COOKEDRABBIT0": "Cooked Rabbit",
            "COOKEDFISH1": "Cooked Salmon",
            "COOKIE0": "Cookie",
            "COBBLESTONESMOOTHBRICK2": "Cracked Stone Bricks",
            "STONEMONSTEREGGS4": "Cracked Stone Bricks Monster Egg",
            "WORKBENCH0": "Crafting Table",
            "SKULLITEM4": "Creeper Head",
            "BANNER6": "Cyan Banner",
            "CARPET9": "Cyan Carpet",
            "CYANDYE6": "Cyan Dye",
            "STAINEDCLAY9": "Cyan Hardened Clay",
            "STAINEDGLASS9": "Cyan Stained Glass",
            "STAINEDGLASSPANE9": "Cyan Stained Glass Pane",
            "CYANWOOL9": "Cyan Wool",
            "YELLOWFLOWER0": "Dandelion",
            "YELLOWDYE11": "Dandelion Yellow",
            "BOATDARKOAK0": "Dark Oak Boat",
            "DARKOAKDOORITEM0": "Dark Oak Door",
            "DARKOAKFENCE0": "Dark Oak Fence",
            "DARKOAKFENCEGATECLOSED": "Dark Oak Fence Gate",
            "DARKOAKDECAYABLEDARKOAKLEAVES21": "Dark Oak Leaves",
            "DARKOAKDARKOAKSAPLING5": "Dark Oak Sapling",
            "DARKOAKUPDARKOAKLOG21": "Dark Oak Wood",
            "DARKOAKWOOD5": "Dark Oak Wood Planks",
            "DARKOAKWOODSTEP5DARKOAK": "Dark Oak Wood Slab",
            "DARKOAKSTAIRS0": "Dark Oak Wood Stairs",
            "PRISMARINE2": "Dark Prismarine",
            "DAYLIGHTDETECTOR0": "Daylight Sensor",
            "DEADBUSH0": "Dead Bush",
            "DETECTORRAIL0": "Detector Rail",
            "DIAMON": "Diamond",
            "DIAMONDAXE": "Diamond Axe",
            "DIAMONDBOOTS": "Diamond Boots",
            "DIAMONDCHESTPLATE": "Diamond Chestplate",
            "DIAMONDHELMET": "Diamond Helmet",
            "DIAMONDHOE": "Diamond Hoe",
            "DIAMONDBARDING0": "Diamond Horse Armor",
            "DIAMONDLEGGINGS": "Diamond Leggings",
            "DIAMONDORE0": "Diamond Ore",
            "DIAMONDPICKAXE": "Diamond Pickaxe",
            "DIAMONDSPADE": "Diamond Shovel",
            "DIAMONDSWORD": "Diamond Sword",
            "STONE3": "Diorite",
            "DIRT0": "Dirt",
            "DISPENSER0": "Dispenser",
            "DOUBLEPLANT2": "Double Tallgrass",
            "SKULLITEM5": "Dragon Head",
            "DRAGONSBREATH0": "Dragon's Breath",
            "DROPPER0": "Dropper",
            "EGG0": "Egg",
            "ELYTRA0": "Elytra",
            "EMERALD0": "Emerald",
            "EMERALDORE0": "Emerald Ore",
            "EMPTYMAP0": "Empty Map",
            "ENCHANTEDBOOK0": "Enchanted Book",
            "ENCHANTMENTTABLE0": "Enchantment Table",
            "ENDCRYSTAL0": "End Crystal",
            "ENDERPORTALFRAME0": "End Portal Frame",
            "ENDROD0": "End Rod",
            "ENDERSTONE0": "End Stone",
            "ENDBRICKS0": "End Stone Bricks",
            "ENDERCHEST0": "Ender Chest",
            "ENDERPEARL0": "Ender Pearl",
            "EYEOFENDER0": "Eye of Ender",
            "FEATHER0": "Feather",
            "FERMENTEDSPIDEREYE0": "Fermented Spider Eye",
            "FERNLIKELONGGRASS2": "Fern",
            "FIREBALL0": "Fire Charge",
            "FIREWORKCHARGE0": "Firework Star",
            "FISHINGROD": "Fishing Rod",
            "FLINT0": "Flint",
            "FLINTANDSTEEL": "Flint and Steel",
            "FLOWERPOTITEM0": "Flower Pot",
            "FURNACE0": "Furnace",
            "GHASTTEAR0": "Ghast Tear",
            "GLASS0": "Glass",
            "GLASSBOTTLE0": "Glass Bottle",
            "THINGLASS0": "Glass Pane",
            "SPECKLEDMELON0": "Glistering Melon",
            "GLOWSTONE0": "Glowstone",
            "GLOWSTONEDUST0": "Glowstone Dust",
            "GOLDAXE": "Gold Axe",
            "GOLDBOOTS": "Gold Boots",
            "GOLDCHESTPLATE": "Gold Chestplate",
            "GOLDHELMET": "Gold Helmet",
            "GOLDLEGGINGS": "Gold Leggings",
            "GOLDNUGGET0": "Gold Nugget",
            "GOLDORE0": "Gold Ore",
            "GOLDPICKAXE": "Gold Pickaxe",
            "GOLDSPADE": "Gold Shovel",
            "GOLDSWORD": "Gold Sword",
            "GOLDENAPPLE": "Golden Apple",
            "GOLDENCARROT0": "Golden Carrot",
            "GOLDHOE": "Golden Hoe",
            "GOLDBARDING0": "Golden Horse Armor",
            "STONE1": "Granite",
            "NORMALLONGGRASS1": "Grass",
            "GRASS0": "Grass Block",
            "GRAVEL0": "Gravel",
            "BANNER8": "Gray Banner",
            "CARPET7": "Gray Carpet",
            "GRAYDYE8": "Gray Dye",
            "STAINEDCLAY7": "Gray Hardened Clay",
            "STAINEDGLASS7": "Gray Stained Glass",
            "STAINEDGLASSPANE7": "Gray Stained Glass Pane",
            "GRAYWOOL7": "Gray Wool",
            "BANNER2": "Green Banner",
            "CARPET13": "Green Carpet",
            "STAINEDCLAY13": "Green Hardened Clay",
            "STAINEDGLASS13": "Green Stained Glass",
            "STAINEDGLASSPANE13": "Green Stained Glass Pane",
            "GREENWOOL13": "Green Wool",
            "SULPHUR0": "Gunpowder",
            "HARDCLAY0": "Hardened Clay",
            "HAYBLOCK0": "Hay Bale",
            "SKULLITEM3": "Head",
            "HOPPER0": "Hopper",
            "ICE0": "Ice",
            "BLACKDYE0": "Ink Sac",
            "IRONAXE": "Iron Axe",
            "IRONFENCE0": "Iron Bars",
            "IRONBOOTS": "Iron Boots",
            "IRONCHESTPLATE": "Iron Chestplate",
            "IRONDOOR0": "Iron Door",
            "IRONHELMET": "Iron Helmet",
            "IRONHOE": "Iron Hoe",
            "IRONBARDING0": "Iron Horse Armor",
            "IRONLEGGINGS": "Iron Leggings",
            "IRONORE0": "Iron Ore",
            "IRONPICKAXE": "Iron Pickaxe",
            "IRONSPADE": "Iron Shovel",
            "IRONSWORD": "Iron Sword",
            "CLOSEDIRONTRAPDOOR0": "Iron Trapdoor",
            "ITEMFRAME0": "Item Frame",
            "JACKOLANTERN0": "Jack o'Lantern",
            "JUKEBOX0": "Jukebox",
            "BOATJUNGLE0": "Jungle Boat",
            "JUNGLEDOORITEM0": "Jungle Door",
            "JUNGLEFENCE0": "Jungle Fence",
            "JUNGLEFENCEGATECLOSED": "Jungle Fence Gate",
            "JUNGLEDECAYABLEJUNGLELEAVES3": "Jungle Leaves",
            "JUNGLEJUNGLESAPLING3": "Jungle Sapling",
            "JUNGLEUPJUNGLELOG3": "Jungle Wood",
            "JUNGLEWOOD3": "Jungle Wood Planks",
            "JUNGLEWOODSTEP3JUNGLE": "Jungle Wood Slab",
            "JUNGLEWOODSTAIRS0": "Jungle Wood Stairs",
            "LADDER0": "Ladder",
            "BLUEDYE4": "Lapis Lazuli",
            "LAPISBLOCK0": "Lapis Lazuli Block",
            "LAPISORE0": "Lapis Lazuli Ore",
            "DOUBLEPLANT3": "Large Fern",
            "LAVABUCKET0": "Lava Bucket",
            "LEASH0": "Lead",
            "LEATHER0": "Leather",
            "LEATHERBOOTS": "Leather Boots",
            "LEATHERHELMET": "Leather Cap",
            "LEATHERLEGGINGS": "Leather Pants",
            "LEATHERCHESTPLATE": "Leather Tunic",
            "LEVER0": "Lever",
            "BANNER12": "Light Blue Banner",
            "CARPET3": "Light Blue Carpet",
            "LIGHTBLUEDYE12": "Light Blue Dye",
            "STAINEDCLAY3": "Light Blue Hardened Clay",
            "STAINEDGLASS3": "Light Blue Stained Glass",
            "STAINEDGLASSPANE3": "Light Blue Stained Glass Pane",
            "LIGHTBLUEWOOL3": "Light Blue Wool",
            "BANNER7": "Light Gray Banner",
            "CARPET8": "Light Gray Carpet",
            "SILVERDYE7": "Light Gray Dye",
            "STAINEDCLAY8": "Light Gray Hardened Clay",
            "STAINEDGLASS8": "Light Gray Stained Glass",
            "STAINEDGLASSPANE8": "Light Gray Stained Glass Pane",
            "SILVERWOOL8": "Light Gray Wool",
            "DOUBLEPLANT1": "Lilac",
            "WATERLILY0": "Lily Pad",
            "BANNER10": "Lime Banner",
            "CARPET5": "Lime Carpet",
            "LIMEDYE10": "Lime Dye",
            "STAINEDCLAY5": "Lime Hardened Clay",
            "STAINEDGLASS5": "Lime Stained Glass",
            "STAINEDGLASSPANE5": "Lime Stained Glass Pane",
            "LIMEWOOL5": "Lime Wool",
            "LINGERINGPOTIONfireresistance": "Lingering Potion of Fire Resistance",
            "LINGERINGPOTIONharming": "Lingering Potion of Harming",
            "LINGERINGPOTIONhealing": "Lingering Potion of Healing",
            "LINGERINGPOTIONinvisibility": "Lingering Potion of Invisibility",
            "LINGERINGPOTIONleaping": "Lingering Potion of Leaping",
            "LINGERINGPOTIONluck": "Lingering Potion of Luck",
            "LINGERINGPOTIONnightvision": "Lingering Potion of Night Vision",
            "LINGERINGPOTIONpoison": "Lingering Potion of Poison",
            "LINGERINGPOTIONregeneration": "Lingering Potion of Regeneration",
            "LINGERINGPOTIONslowness": "Lingering Potion of Slowness",
            "LINGERINGPOTIONstrength": "Lingering Potion of Strength",
            "LINGERINGPOTIONswiftness": "Lingering Potion of Swiftness",
            "LINGERINGPOTIONwaterbreathing": "Lingering Potion of Water Breathing",
            "LINGERINGPOTIONweakness": "Lingering Potion of Weakness",
            "LINGERINGPOTIONwater": "Lingering Water Bottle",
            "BANNER13": "Magenta Banner",
            "CARPET2": "Magenta Carpet",
            "MAGENTADYE13": "Magenta Dye",
            "STAINEDCLAY2": "Magenta Hardened Clay",
            "STAINEDGLASS2": "Magenta Stained Glass",
            "STAINEDGLASSPANE2": "Magenta Stained Glass Pane",
            "MAGENTAWOOL2": "Magenta Wool",
            "MAGMACREAM0": "Magma Cream",
            "MELON0": "Melon",
            "MELONSEEDS0": "Melon Seeds",
            "MILKBUCKET0": "Milk",
            "MINECART0": "Minecart",
            "STORAGEMINECART0": "Minecart with Chest",
            "POWEREDMINECART0": "Minecart with Furnace",
            "HOPPERMINECART0": "Minecart with Hopper",
            "EXPLOSIVEMINECART0": "Minecart with TNT",
            "MOSSYCOBBLESTONE0": "Moss Stone",
            "COBBLEWALL1": "Mossy Cobblestone Wall",
            "MOSSYCOBBLESTONESMOOTHBRICK1": "Mossy Stone Bricks",
            "STONEMONSTEREGGS3": "Mossy Stone Bricks Monster Egg",
            "LINGERINGPOTIONmundane": "Mundane Lingering Potion",
            "POTIONmundane": "Mundane Potion",
            "SPLASHPOTIONmundane": "Mundane Splash Potion",
            "MUSHROOMSOUP0": "Mushroom Stew",
            "MYCEL0": "Mycelium",
            "NAMETAG0": "Name Tag",
            "NETHERBRICK0": "Nether Brick",
            "NETHERBRICKITEM0": "Nether Brick (item)",
            "NETHERFENCE0": "Nether Brick Fence",
            "NETHERBRICKSTEP6": "Nether Brick Slab",
            "NETHERBRICKSTAIRS0": "Nether Brick Stairs",
            "QUARTZ0": "Nether Quartz",
            "NETHERSTAR0": "Nether Star",
            "NETHERSTALK0": "Nether Wart",
            "NETHERWARTBLOCK0": "Nether Wart (block)",
            "NETHERWARTBLOCK0": "Nether Wart Block",
            "NETHERRACK0": "Netherrack",
            "NOTEBLOCK0": "Note Block",
            "BOAT0": "Oak Boat",
            "WOODDOOR0": "Oak Door",
            "FENCE0": "Oak Fence",
            "FENCEGATECLOSED": "Oak Fence Gate",
            "GENERICDECAYABLEGENERICLEAVES0": "Oak Leaves",
            "GENERICGENERICSAPLING0": "Oak Sapling",
            "GENERICUPGENERICLOG0": "Oak Wood",
            "GENERICWOOD0": "Oak Wood Planks",
            "GENERICWOODSTEP0GENERIC": "Oak Wood Slab",
            "WOODSTAIRS0": "Oak Wood Stairs",
            "OBSIDIAN0": "Obsidian",
            "BANNER14": "Orange Banner",
            "CARPET1": "Orange Carpet",
            "ORANGEDYE14": "Orange Dye",
            "STAINEDCLAY1": "Orange Hardened Clay",
            "STAINEDGLASS1": "Orange Stained Glass",
            "STAINEDGLASSPANE1": "Orange Stained Glass Pane",
            "REDROSE5": "Orange Tulip",
            "ORANGEWOOL1": "Orange Wool",
            "REDROSE8": "Oxeye Daisy",
            "PACKEDICE0": "Packed Ice",
            "PAINTING0": "Painting",
            "PAPER0": "Paper",
            "DOUBLEPLANT5": "Peony",
            "QUARTZBLOCK2": "Pillar Quartz Block",
            "BANNER9": "Pink Banner",
            "CARPET6": "Pink Carpet",
            "PINKDYE9": "Pink Dye",
            "STAINEDCLAY6": "Pink Hardened Clay",
            "STAINEDGLASS6": "Pink Stained Glass",
            "STAINEDGLASSPANE6": "Pink Stained Glass Pane",
            "REDROSE7": "Pink Tulip",
            "PINKWOOL6": "Pink Wool",
            "PISTONBASE0": "Piston",
            "DIRT2": "Podzol",
            "POISONOUSPOTATO0": "Poisonous Potato",
            "STONE6": "Polished Andesite",
            "STONE4": "Polished Diorite",
            "STONE2": "Polished Granite",
            "CHORUSFRUITPOPPED0": "Popped Chorus Fruit",
            "REDROSE0": "Poppy",
            "POTATOITEM0": "Potato",
            "POTIONfireresistance": "Potion of Fire Resistance",
            "POTIONharming": "Potion of Harming",
            "POTIONhealing": "Potion of Healing",
            "POTIONinvisibility": "Potion of Invisibility",
            "POTIONleaping": "Potion of Leaping",
            "POTIONluck": "Potion of Luck",
            "POTIONnightvision": "Potion of Night Vision",
            "POTIONpoison": "Potion of Poison",
            "POTIONregeneration": "Potion of Regeneration",
            "POTIONslowness": "Potion of Slowness",
            "POTIONstrength": "Potion of Strength",
            "POTIONswiftness": "Potion of Swiftness",
            "POTIONwaterbreathing": "Potion of Water Breathing",
            "POTIONweakness": "Potion of Weakness",
            "POWEREDRAIL0": "Powered Rail",
            "PRISMARINE1": "Prismarine Bricks",
            "PRISMARINECRYSTALS0": "Prismarine Crystals",
            "PRISMARINESHARD0": "Prismarine Shard",
            "RAWFISH3": "Pufferfish",
            "PUMPKIN0": "Pumpkin",
            "PUMPKINPIE0": "Pumpkin Pie",
            "PUMPKINSEEDS0": "Pumpkin Seeds",
            "BANNER5": "Purple Banner",
            "CARPET10": "Purple Carpet",
            "PURPLEDYE5": "Purple Dye",
            "STAINEDCLAY10": "Purple Hardened Clay",
            "STAINEDGLASS10": "Purple Stained Glass",
            "STAINEDGLASSPANE6": "Purple Stained Glass Pane",
            "PURPLEWOOL10": "Purple Wool",
            "PURPURBLOCK0": "Purpur Block",
            "PURPURPILLAR0": "Purpur Pillar",
            "PURPURSLAB0": "Purpur Slab",
            "PURPURSTAIRS0": "Purpur Stairs",
            "QUARTZBLOCKSTEP7": "Quartz Slab",
            "QUARTZSTAIRS0": "Quartz Stairs",
            "RABBITHIDE0": "Rabbit Hide",
            "RABBITSTEW0": "Rabbit Stew",
            "RABBITFOOT0": "Rabbit's Foot",
            "RAILS0": "Rail",
            "RAILS0": "Rails",
            "RAWBEEF0": "Raw Beef",
            "RAWCHICKEN0": "Raw Chicken",
            "RAWFISH0": "Raw Fish",
            "MUTTON0": "Raw Mutton",
            "PORK0": "Raw Porkchop",
            "RABBIT0": "Raw Rabbit",
            "RAWFISH1": "Raw Salmon",
            "BANNER1": "Red Banner",
            "CARPET14": "Red Carpet",
            "STAINEDCLAY14": "Red Hardened Clay",
            "REDMUSHROOM0": "Red Mushroom",
            "REDNETHERBRICK0": "Red Nether Brick",
            "SAND1": "Red Sand",
            "REDSANDSTONE0": "Red Sandstone",
            "STONESLAB20": "Red Sandstone Slab",
            "REDSANDSTONESTAIRS0": "Red Sandstone Stairs",
            "STAINEDGLASS14": "Red Stained Glass",
            "STAINEDGLASSPANE14": "Red Stained Glass Pane",
            "REDROSE4": "Red Tulip",
            "REDWOOL14": "Red Wool",
            "REDSTONE0": "Redstone",
            "REDSTONECOMPARATOR0": "Redstone Comparator",
            "REDSTONELAMPOFF0": "Redstone Lamp",
            "REDSTONEORE0": "Redstone Ore",
            "DIODE0": "Redstone Repeater",
            "REDSTONETORCHON0": "Redstone Torch",
            "DOUBLEPLANT4": "Rose Bush",
            "REDDYE1": "Rose Red",
            "ROTTENFLESH0": "Rotten Flesh",
            "SADDLE": "Saddle",
            "SAND0": "Sand",
            "CRACKEDSANDSTONE0": "Sandstone",
            "SANDSTONESTEP1": "Sandstone Slab",
            "SANDSTONESTAIRS0": "Sandstone Stairs",
            "SEEDS0": "Seeds",
            "SHEARS": "Shears",
            "SHIELD": "Shield",
            "SIGN0": "Sign",
            "SKULLITEM0": "Skeleton Skull",
            "ANVIL": "Slightly Damaged Anvil",
            "SLIMEBLOCK0": "Slime Block",
            "SLIMEBALL0": "Slimeball",
            "REDSANDSTONE2": "Smooth Red Sandstone",
            "SMOOTHSANDSTONE2": "Smooth Sandstone",
            "SNOWBLOCK0": "Snow",
            "SNOW0": "Snow (layer)",
            "SNOWBALL0": "Snowball",
            "SOULSAND0": "Soul Sand",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWB2SixhYAAAbnymwBsAAAA": "Spawn Bat",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWB1ykmsSmVgAAD4nt7HQAAAA": "Spawn Blaze",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeByTixLDS7ITEktYmAAAAPjG5IiAAAA": "Spawn Cave Spider",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWB3zshMzk7NY2AAAGifiu0fAAAA": "Spawn Chicken",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWB2zi9nYAAAtJxfHxsAAAA": "Spawn Cow",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWB3LkpNLUgtYmAAAGXHBBMfAAAA": "Spawn Creeper",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeBwzUtJLcpNzGNgAAB2vyyKIAAAAA": "Spawn Enderman",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMAfFTUotyM0tSGRgApa6DsSEAAAA": "Spawn Endermite",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWB1z0gsLmFgAACDCT7SHQAAAA": "Spawn Ghast",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeBwL00sSslMzGNgAACFWNpqIAAAAA": "Spawn Guardian",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeCG8D3yi4pTGRgA104FmCMAAAA": "Spawn Horse",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeD0SSxLDM7JzE1lYAAAOFY+siEAAAA": "Spawn Magma Cube",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeD2LS3OKMrPz3XOL2dgAADFQ0VuIwAAAA": "Spawn Mooshroom",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWDzr0rNyS9hYAAA3vuJER4AAAA": "Spawn Ocelot",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWAOyExnYAAASo1SARsAAAA": "Spawn Pig",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeAMyM9JLHJKTSxiYAAASknW8yEAAAA": "Spawn Polar Bear",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWALSkxKyixhYAAAFcawFB4AAAA": "Spawn Rabbit",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzkhNLWBgAAABt1TGHQAAAA": "Spawn Sheep",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWAPzijNyU4tYmAAAGLDXgUfAAAA": "Spawn Shulker",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeAKzswpSy1KyyzOYGAAAH2TOTgiAAAA": "Spawn Silverfish",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeAIzk7NSS3Jz2NgAAA4sUgIAAAAA": "Spawn Skeleton",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzsnMTWVgAABiUWxHHQAAAA": "Spawn Slime",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWALLshMSS1iYAAAmJdvsh4AAAA": "Spawn Spider",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANLiwFUgwAxMeU0x0AAAA": "Spawn Squid",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeAIy8zJSUxPLWJgAADlEwUxIAAAAA": "Spawn Villager",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzyxJzmBgAACRU5mTHQAAAA": "Spawn Witch",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWAJz89JY2AAAIves4gcAAAA": "Spawn Wolf",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWCLys9NykxlYAAAb93Yex4AAAA": "Spawn Zombie",
            "H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYeAMyEyPys9NykxlYAAAHOM0OiEAAAA": "Spawn Zombie Pigman",
            "SPECTRALARROW0": "Spectral Arrow",
            "SPIDEREYE0": "Spider Eye",
            "SPLASHPOTIONmundane": "Splash Mundane Potion",
            "SPLASHPOTIONfireresistance": "Splash Potion of Fire Resistance",
            "SPLASHPOTIONharming": "Splash Potion of Harming",
            "SPLASHPOTIONhealing": "Splash Potion of Healing",
            "SPLASHPOTIONinvisibility": "Splash Potion of Invisibility",
            "SPLASHPOTIONleaping": "Splash Potion of Leaping",
            "SPLASHPOTIONluck": "Splash Potion of Luck",
            "SPLASHPOTIONnightvision": "Splash Potion of Night Vision",
            "SPLASHPOTIONpoison": "Splash Potion of Poison",
            "SPLASHPOTIONregeneration": "Splash Potion of Regeneration",
            "SPLASHPOTIONslowness": "Splash Potion of Slowness",
            "SPLASHPOTIONstrength": "Splash Potion of Strength",
            "SPLASHPOTIONswiftness": "Splash Potion of Swiftness",
            "SPLASHPOTIONwaterbreathing": "Splash Potion of Water Breathing",
            "SPLASHPOTIONweakness": "Splash Potion of Weakness",
            "SPLASHPOTIONwater": "Splash Water Bottle",
            "SPONGE0": "Sponge",
            "BOATSPRUCE0": "Spruce Boat",
            "SPRUCEDOORITEM0": "Spruce Door",
            "SPRUCEFENCE0": "Spruce Fence",
            "SPRUCEFENCEGATECLOSED": "Spruce Fence Gate",
            "REDWOODDECAYABLEREDWOODLEAVES1": "Spruce Leaves",
            "REDWOODREDWOODSAPLING1": "Spruce Sapling",
            "REDWOODUPREDWOODLOG1": "Spruce Wood",
            "REDWOODWOOD1": "Spruce Wood Planks",
            "REDWOODWOODSTEP1REDWOOD": "Spruce Wood Slab",
            "SPRUCEWOODSTAIRS0": "Spruce Wood Stairs",
            "COOKEDBEEF0": "Steak",
            "STICK0": "Stick",
            "PISTONSTICKYBASE0": "Sticky Piston",
            "STONE0": "Stone",
            "STONEAXE": "Stone Axe",
            "SMOOTHSTAIRS0": "Stone Brick Stairs",
            "STONESMOOTHBRICK0": "Stone Bricks",
            "SMOOTHBRICKMONSTEREGGS2": "Stone Bricks Monster Egg",
            "SMOOTHBRICKSTEP5": "Stone Bricks Slab",
            "STONEBUTTON0": "Stone Button",
            "STONEHOE": "Stone Hoe",
            "STONEMONSTEREGGS0": "Stone Monster Egg",
            "STONEPICKAXE": "Stone Pickaxe",
            "STONEPLATE0": "Stone Pressure Plate",
            "STONESPADE": "Stone Shovel",
            "STONESTEP0": "Stone Slab",
            "STONESWORD": "Stone Sword",
            "STRING0": "String",
            "SUGAR0": "Sugar",
            "SUGARCANE0": "Sugar Cane",
            "SUGARCANE0": "Sugar Canes",
            "DOUBLEPLANT0": "Sunflower",
            "TNT0": "TNT",
            "DOUBLEPLANT2": "Tall Grass",
            "LINGERINGPOTIONmundane": "Thick Lingering Potion",
            "POTIONthick": "Thick Potion",
            "SPLASHPOTIONthick": "Thick Splash Potion",
            "TORCH0": "Torch",
            "TRAPPEDCHEST0": "Trapped Chest",
            "TRIPWIREHOOK0": "Tripwire Hook",
            "ANVIL": "Very Damaged Anvil",
            "VINE": "Vines",
            "POTIONwater": "Water Bottle",
            "WATERBUCKET0": "Water Bucket",
            "IRONPLATE0": "Weighted Pressure Plate (Heavy)",
            "GOLDPLATE0": "Weighted Pressure Plate (Light)",
            "SPONGE1": "Wet Sponge",
            "WHEAT0": "Wheat",
            "BANNER15": "White Banner",
            "CARPET0": "White Carpet",
            "STAINEDCLAY0": "White Hardened Clay",
            "STAINEDGLASS0": "White Stained Glass",
            "STAINEDGLASSPANE0": "White Stained Glass Pane",
            "REDROSE6": "White Tulip",
            "WHITEWOOL0": "White Wool",
            "SKULLITEM1": "Wither Skeleton Skull",
            "WOODAXE": "Wooden Axe",
            "WOODBUTTON0": "Wooden Button",
            "WOODHOE": "Wooden Hoe",
            "WOODSPADE": "Wooden Pickaxe",
            "WOODPLATE0": "Wooden Pressure Plate",
            "WOODSPADE": "Wooden Shovel",
            "WOODSWORD": "Wooden Sword",
            "CLOSEDTRAPDOOR0": "Wooden Trapdoor",
            "BANNER11": "Yellow Banner",
            "CARPET4": "Yellow Carpet",
            "STAINEDCLAY4": "Yellow Hardened Clay",
            "STAINEDGLASS4": "Yellow Stained Glass",
            "STAINEDGLASSPANE4": "Yellow Stained Glass Pane",
            "YELLOWWOOL4": "Yellow Wool",
            "SKULLITEM2": "Zombie Head",
            "RECORD30": "blocks Disc",
            "GREENRECORD0": "cat Disc",
            "RECORD40": "chirp Disc",
            "RECORD50": "far Disc",
            "RECORD60": "mall Disc",
            "RECORD70": "mellohi Disc",
            "RECORD80": "stal Disc",
            "RECORD90": "strad Disc",
            "RECORD120": "wait Disc",
            "RECORD100": "ward Disc"
        };

    }]);
});
